[platformio]
default_envs = cardputer_adv

[env:cardputer_adv]
platform = espressif32@6.6.0
board = m5stack-stamps3
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.partitions = partitions_8mb_voice.csv
board_upload.flash_size = 8MB
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=3
    -D M5CARDPUTER
    -D DEVICE_TYPE=\"cardputer_adv\"
    -D DEVICE_NAME=\"ADV\ Cardputer\"
    -D APP_VERSION=\"0.2.1-dev\"
    -D BUILD_GIT_SHA=\"${sysenv.BUILD_GIT_SHA}\"
    -D BUILD_TIME=\"${sysenv.BUILD_TIME}\"
    -D DEFAULT_WIFI_SSID=\"${sysenv.DEFAULT_WIFI_SSID}\"
    -D DEFAULT_WIFI_PASSWORD=\"${sysenv.DEFAULT_WIFI_PASSWORD}\"
    -D DEFAULT_HUB_HOST=\"${sysenv.DEFAULT_HUB_HOST}\"
    -D DEFAULT_HUB_PORT_STR=\"${sysenv.DEFAULT_HUB_PORT}\"
    -D DEFAULT_DEVICE_ID=\"${sysenv.DEFAULT_DEVICE_ID}\"
    -D DEFAULT_DEVICE_TOKEN=\"${sysenv.DEFAULT_DEVICE_TOKEN}\"
    -std=gnu++17

lib_deps =
    m5stack/M5Cardputer@1.0.3
    bblanchon/ArduinoJson@^6.21.4
    links2004/WebSockets@^2.4.1
    adafruit/Adafruit TCA8418@^1.0.2
