[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; ============================================================
; CRITICAL MEMORY SETTINGS (DO NOT CHANGE)
; This enables the 8MB of PSRAM needed for Audio + Camera
; ============================================================
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    esp32-camera
    moononournation/GFX Library for Arduino @ 1.4.7
    bblanchon/ArduinoJson @ ^6.21.3
    links2004/WebSockets @ ^2.4.1
    fbiego/CST816S @ ^1.1.1 ; <-- ADD THIS